version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - eliasnorrby
  versioning-strategy: widen
  ignore:
  - dependency-name: "@eliasnorrby/prettier-config"
    versions:
    - 4.2.19
    - 4.2.23
    - 4.2.24
    - 4.2.26
    - 4.2.27
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@eliasnorrby/log-util"
    versions:
    - 1.1.8
    - 1.1.9
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.8
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: "@types/yargs"
    versions:
    - 16.0.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
