sudo: false
language: node_js
node_js:
- 8
- 11
script:
- npm run lint
- "./setup.test.sh"
jobs:
  include:
  - stage: release
    if: branch = master
    node_js: lts/*
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
notifications:
  slack:
    secure: SUzH83RJhGdrmDrKUbhCb8S9mY693rDGYiB8EapyfgrlQdHeMtvf6RAG9aSVgJd8ZGsXCykm3snN8c+/huM9DvPgV5rY3vvKLBFotqa5VG6YL/vkcuR3FfwQcShiR/bpX0s7swPWDXUgyBzqqAMWhIao6mmWFt/2kUc9+gqm1VbNOvxhBiloFwCpnzH+p6DDJhnbCn06uClYkmw0bu659njVDZv4sxJSySsJkzSRqv8MKfWYt00vI7iTH4HjTus7zox1fCr30txDShDBoloBwGyhtxWjeJFOr8067y6A9WXdA8hY7ypOPoyw/qrXj04OPtAYRZ7FswOBTH5SlCeqSXy2p2Upqoi7FSSKCy1rW8ubg4cVLbj5m/QWKb38+uLsbeyG3pYSJ4zqYzzXh0I92YEDkTU/8RyC5atTJCpANNkaASP58G0skA6A2ZzHJlWXyi7H4RE16he5yNrHPgz0cxHduCYQhOCTolS3yNP18AKj0GAnITH/31QvU1lQ4IKzSgzxsopQ/QzBDw5pcw5aalMVzF6nQDqCadJsSCUsN0FqH5K/gsGT8pSLR1GQsW079IRw5B+muL9JPdCJGccYkk7K4h+4Ihtdkx1JQFcg/ypZHK/iXTCkA2riMkIWCOHqxVxxnAMROS21PNuf/j7A4PM9BRd6T9Dnc3wZaPbnRmM=
